version: 0.0
Resources:
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: auth-backend
        Alias: auth-backend-aly
        CurrentVersion: 1
        TargetVersion: 1
Hooks:
  - BeforeAllowTraffic: "LambdaFunctionToUpdate"
  - AfterAllowTraffic: "LambdaFunctionToValidate"