version: 0.0
Resources:
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: auth-backend
        Alias: auth-backend-aly
        CurrentVersion: "$LATEST"  # Use $LATEST to refer to the latest version
        TargetVersion: "1"  # Specify a valid version, if it exists
