version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn clean install  # Install the dependencies for the project

  build:
    commands:
      - echo Building the Lambda JAR...
      - mvn clean package  # Build the JAR file in the target directory

artifacts:
  files:
    - target/auth-backend-1.0.jar  # This is the JAR file to deploy
    - appspec.yml                  # Include the appspec.yml file for deployment
  discard-paths: yes                 # Ensures the paths in the artifact are clean (i.e., no extra directories)
