version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - mvn clean install
  build:
    commands:
      - echo "Building JAR..."
      - mvn package
  post_build:
    commands:
      - echo "Creating appspec.yml..."
      - |
        cat << EOF > appspec.yml
        version: 0.0
        Resources:
          - auth-function:
              Type: AWS::Lambda::Function
              Properties:
                Name: "${ProjectName}-auth-function"
                Alias: LIVE
                CurrentVersion: "\$LATEST"
                TargetVersion: "\$LATEST"
        EOF

artifacts:
  files:
    - target/auth-backend-1.0.jar
    - appspec.yml
  discard-paths: yes