version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn clean install

  build:
    commands:
      - echo Building the Lambda JAR...
      - mvn clean package

  post_build:
    commands:
      - echo Updating Lambda function code...
      - aws lambda update-function-code
        --function-name auth-backend
        --zip-file fileb://target/auth-backend-1.0.jar

artifacts:
  files:
    - target/auth-backend-1.0.jar
    - appspec.yml
  discard-paths: yes