version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn clean install
  build:
    commands:
      - echo Building the Lambda JAR...
      - mvn clean package # This will create the JAR file in the 'target' directory

artifacts:
  files:
    - target/*.jar # Ensure that the built JAR file is available for the next stage
